title: Ahmed Tealeb Bio
author: ahtealeb
email: 
description: > # this means to ignore newlines until "baseurl:"
 PhD. of Information Systems, BPM, CBPA, BA, ITIL®, Agile, BI, SQA, Data Analytics and Visualization, Python, Blockchains.



# social links
twitter_username: ahtealeb
github_username:  ahtealeb

show_excerpts: false # set to false to remove excerpts on the homepage

theme: minima
