title: Ahmed Tealeb Bio
author: Ahmed Tealeb
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  PhD. of Information Systems, 
  BPM, CBPA, BA, ITIL®, Agile, BI, 
  SQA, Data Analytics and Visualization, 
  Python, Blockchains

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
